- name: Create Containers
  shell: . /etc/profile; ncli ctr create name="{{ item }}" sp-id=`ncli sp ls | grep Id | grep -v Disk | cut -f 4 -d :`
  loop:
     - ctr1
     - ctr2
     - DR
     - Images
     - VGs
