---
"pc_ip": "10.63.31.115"
"afs_name": "pilotwings-fs"
"afs_domain": "dur.sre-labs.nutanix.com"
"afs_admin": "administrator"
"afs_dns": "10.63.25.40"
"afs_ntp": "10.63.25.20"
"afs_admin_pwd": "SREs4eva!"
"internal_pool": "10.63.31.111 10.63.31.114"
"external_pool": ""
"vg_name" : "pilotwings-vg"
"dsip": "10.63.28.115"
"oss_start": ""
"oss_end": ""
"oss_domain": "dur-sre-labs.nutanix.com"
"oss_name": "pilotwings-fs"
"ipam_start": ""
"ipam_end": ""
"cvm1": "10.63.30.111"
"cvm2": "10.63.30.112"
"cvm3": "10.63.30.113"
"cvm4": "10.63.30.114"
"host1": "10.63.29.111"
"host2": "10.63.29.112"
"host3": "10.63.29.113"
"host4": "10.63.29.114"
"ipmi1": "10.63.28.111"
"ipmi2": "10.63.28.112"
"ipmi3": "10.63.28.113"
"ipmi4": "10.63.28.114"

