- name: Get Cluster Container for PC installation 
  hosts: frog 
  become: no
  gather_facts: no 
  ignore_errors: yes
  vars:
  roles: 
  tasks: 
    - name: Get Container UUID
        shell: . /etc/profile; ncli ctr ls | grep Uuid | grep -v Storage | cut -f2 -d:
