- name: Downloading Prism Central
  hosts: startropics
  become: no
  gather_facts: yes
  vars:
  roles:
  tasks:
    - name: Downloading Prism Central to cluster
      uri:
        url:  https://{{ansible_default_ipv4.address}}:9440/api/nutanix/v3/prism_central`
        metod: POST
        body_format: json
        body: "{{lookup('file',pc.json')}}"
        user: admin
        password: zxm4=py25PVs:Aw
        force_basic_auth: yes
        return_content: yes
        validate_certs: no
