---
- name: Configuring Basic Cluster Setup
  hosts: setup
  become: no
  gather_facts: yes
  vars:
    pwd: "nx2Tech791!" 
  pre_tasks:
    - debug:
        msg: 'Staring Configration'

  roles:
    - ahv

  post_tasks:
    - debug:
        msg: 'Cluster configuration Complete'

