---
- name: Configuring Basic Cluster Setup
  hosts: setup_hyperv
  become: no
  gather_facts: yes
  vars:
    pwd: "zxm4=py25PVs:Aw"
  pre_tasks:
    - debug:
        msg: 'Staring Configration'

  roles:
    - hyperv
  post_tasks:
    - debug:
        msg: 'Cluster configuration Complete'

