---
- name: Configuring Basic Cluster Setup
  hosts: setup_esxi
  become: no
  gather_facts: yes
  vars:
  pre_tasks:
    - debug:
        msg: 'Staring Configration'

  roles:
    - esxi 
  post_tasks:
    - debug:
        msg: 'Cluster configuration Complete'

