---
- name: Configure Openldap Server
  hosts: openldap
  become: yes
  vars:
  roles:
  tasks:
  #- name: Disable SELINUX
  #  shell: setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  - name: Install Software Requirements
    yum:
      name: "{{packages}}"
    vars:
      packages:
        - openldap
        - compat-openldap
        - openldap-clients
        - openldap-servers
        - openldap-devel
  - name: Disable TLS
    shell: sed -i 's/olcTLSC/#olcTLSC/' /etc/openldap/slapd.d/cn=config.ldif

  - name: Starting Openldap Server
    service:
      name: slapd
      state: started
      enabled: yes
  - name: Copy Sample Configuration to /var/lib/DB_CONFIG
    copy:
      src: /usr/share/openldap-servers/DB_CONFIG.example
      dest: /var/lib/ldap/DB_CONFIG
      owner: ldap
      group: ldap
    notify: restart_slapd

  handlers:
  - name: restart_slapd
    service:
      name: slapd
      state: restart

