---
- name: Configuring Basic Cluster Setup
  hosts: setup
  become: no
  gather_facts: yes
  ignore_errors: yes 
  vars:
  vars_prompt:
  pre_tasks:
    - debug:
        msg: 'Staring Configration'

  roles:
    - hyperv
  post_tasks:
    - debug:
        msg: 'Cluster configuration Complete'

