- name: Creating Managed Network for OSS 
  hosts: setup 
  become: no
  gather_facts: yes
  vars:
  vars_prompt:
    - name: ipam_start
      prompt: "Please enter first IP address of DHCP Pool"
      private: no
    - name: ipam_end
      prompt: "Please enter last IP address of DHCP Pool"
      private: no
  roles:
  tasks:
    - name: Creating IPAM Network
      shell: . /etc/profile; acli net.create IPAM vlan=101 ip_config=10.63.21.1/24; acli net.add_dhcp_pool IPAM start={{ipam_start}} end={{ipam_end}}; acli net.update_dhcp_dns IPAM server=10.63.25.40 domains={{afs_domain}};
