---
- name: Deploying Nutanix Files
  hosts: setup
  become: no
  gather_facts: yes
  vars:
  vars_prompt:
    - name: external_pool 
      prompt: "Please enter the IP Address Range (3 IPs) for the External Network resvered from Eevee.SRE-Labs.Nutanix.com"
      private: no
  roles:
    - afs-deploy 
  tasks:
