- name: Dowloading Prism Central and Files software
  hosts: setup
  become: no
  gather_facts: yes
  ignore_errors: yes
  vars:
    pc_ver: pc.2020.9
    afs_ver: 3.7.1 
  roles:
  tasks:
    - name: Downloading PC Bits
      shell: . /etc/profile; ncli software download software-type=Prism_Central_Deploy name={{pc_ver}}
    - name: Downloading Files Bits
      shell: . /etc/profile; ncli software download software-type=files name={{afs_ver}}
