- name: Enable  Microsegmentation for Prism Central
  hosts: setup_pc
  become: no
  gather_facts: yes
  vars:
  roles:
  tasks:
    - name: Enabling Microseg
      uri:
        url: "https://{{ansible_default_ipv4.address}}:9440/api/nutanix/v3/services/microseg"
        method: POST
        validate_certs: no
        user: "admin"
        password: "{{pwd}}"
        body_format: json
        body:
          state: ENABLE
        force_basic_auth: yes
        status_code: 202
      register: output 
