- name: End User Aggreement
  hosts: startropics
  become: no
  gather_facts: no
  vars:
  roles:
  tasks:
    - name: Get Eula
      uri:
       url: https://10.63.30.215:9440/api/nutanix/v1/eulas
       method: GET
       user: admin
       password: zxm4=py25PVs:Aw
       force_basic_auth: yes
       return_content: yes
       validate_certs: no
