- name: Join Hyper-V Cluster to AD Domain
  hosts: setup
  become: yes
  gather_facts: yes 
  vars:
  roles:
  tasks:
    - set_fact:
        request: "{{lookup('template','hyperv-req.j2') | from_yaml | to_json}}"
    - debug:
        msg: "{{request}}"

    - name: join domain
      uri:
        url: "https://{{ansible_default_ipv4.address}}:9440/PrismGateway/services/rest/v1/cluster/join_all_to_domain"
        user: admin
        method: POST
        password: "{{pwd}}"
        body_format: json
        body: "{{request}}"
        force_basic_auth: yes
        status_code: 201
        validate_certs: no
