---
- name: Deploying Prism Central 
  hosts: setup
  become: no
  gather_facts: yes
  vars:
  pre_tasks:
    - debug:
        msg: 'Staring Configration'

  roles:
    - pc-register 

  post_tasks:
    - debug:
        msg: 'Cluster configuration Complete'

