[setup]
magicaldrop ansible_password=nx2Tech325!
[setup:vars]
pwd=nx2Tech325!

[setup_pc]
magicaldrop_pc
[setup_pc:vars]
pc_pwd=nx2Tech325!

[hyperv]
magicaldrop-1  ansible_host=10.63.29.91
magicaldrop-2  ansible_host=10.63.29.92
magicaldrop-3  ansible_host=10.63.29.93
magicaldrop-4  ansible_host=10.63.29.94

[hyperv:vars]
ansible_user=administrator
ansible_password=nutanix/4u
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore



[windows]
magicaldrop-vm1 ansible_host=10.63.22.161
magicaldrop-vm2 ansible_host=10.63.23.209

[windows:vars]
ansible_user=administrator
ansible_password=nutanix/4u
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore


[all:vars]
pwd=nx2Tech325!
pc_pwd=nx2Tech325!

